# Generated by Django 6.0.3 on 2026-03-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('BALANCE', 'Balance'), ('TECHNIQUE', 'Technique'), ('SPEED', 'Speed'), ('POWER', 'Power')], max_length=16)),
                ('curve_ball_speed', models.PositiveSmallIntegerField()),
                ('fast_ball_speed', models.PositiveSmallIntegerField()),
                ('curve', models.PositiveSmallIntegerField()),
                ('throw_power', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('slap_hit_power', models.PositiveSmallIntegerField()),
                ('charge_hit_power', models.PositiveSmallIntegerField()),
                ('bunting', models.PositiveSmallIntegerField()),
                ('height', models.FloatField()),
                ('dive_range', models.FloatField()),
                ('bat_reach', models.PositiveSmallIntegerField()),
                ('full_charge_frames', models.PositiveSmallIntegerField()),
                ('wall_splat', models.BooleanField(default=False)),
                ('curved_hits', models.BooleanField(default=False)),
                ('star_pitch', models.CharField(choices=[('FASTBALL', 'Fastball'), ('CHANGEUP', 'Changeup'), ('CURVEBALL', 'Curveball')], max_length=16)),
                ('star_swing', models.CharField(choices=[('POP_FLY', 'Pop Fly'), ('GROUNDER', 'Grounder'), ('LINE_DRIVE', 'Line Drive')], max_length=16)),
                ('horizontal_hit_trajectory', models.CharField(choices=[('PULL', 'Pull'), ('MID', 'Mid'), ('PUSH', 'Push')], max_length=4)),
                ('vertical_hit_trajectory', models.CharField(choices=[('HIGH', 'High'), ('MID', 'Mid'), ('LOW', 'Low')], max_length=4)),
                ('abilities', models.ManyToManyField(related_name='characters', to='stats.ability')),
                ('anti_chemistry', models.ManyToManyField(blank=True, related_name='anti_chemistry', to='stats.character')),
                ('chemistry', models.ManyToManyField(blank=True, related_name='chemistry', to='stats.character')),
            ],
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.character')),
                ('captain_star_pitch', models.CharField(max_length=16)),
                ('captain_star_swing', models.CharField(max_length=16)),
            ],
            bases=('stats.character',),
        ),
    ]
