# Generated by Django 6.0.3 on 2026-03-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
