# Generated by Django 6.0.3 on 2026-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
        migrations.AddField(
            model_name='character',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='character_icons/'),
        ),
        migrations.AddField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='character_portraits/'),
        ),
        migrations.AddField(
            model_name='character',
            name='variants',
            field=models.ManyToManyField(blank=True, to='stats.character'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='anti_chemistry',
            field=models.ManyToManyField(blank=True, to='stats.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='chemistry',
            field=models.ManyToManyField(blank=True, to='stats.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
