# Generated by Django 6.0.3 on 2026-03-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_ability_options_character_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='captain_star_pitch',
            new_name='captain_star_ability',
        ),
        migrations.RemoveField(
            model_name='captain',
            name='captain_star_swing',
        ),
    ]
