# Generated by Django 6.0.3 on 2026-03-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_ability_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='captain_star_ability',
            new_name='star_ability',
        ),
    ]
