# Generated by Django 6.0.3 on 2026-03-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_rename_captain_star_pitch_captain_captain_star_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cursed_ball',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='character',
            name='main_variant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='trimmed_bat',
            field=models.BooleanField(default=False),
        ),
    ]
